apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: promote
spec:
  params:
    - name: gh-secret
      type: string
      default: github-auth
  workspaces:
    - name: source
      description: A workspace that contains the fetched git repository.
  steps:
    - name: foo
      image: ubuntu
      workingDir: $(workspaces.source.path)
      script: |
        ls -alh .
    - name: create-branch
      image: alpine/git:v2.30.2
      workingDir: $(workspaces.source.path)
      script: |
        git config --global user.email "tekton-botski@users.noreply.github.com"
        git config --global user.name "tekton"
        git status
        echo "foo" > apa.txt
        git checkout -b test-pr-1
        git add apa.txt
        git commit -m "test"
        git push origin test-pr-1
    - name: using-creds
      image: curlimages/curl
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.gh-secret)
              key: password
      script: |
        echo "$GITHUB_TOKEN"
        curl \
        -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/sata/tekton-experiment/pulls \
        -d '{"head":"test-pr-1","base":"master", "title":"yo, merge this!"}'
